apiVersion: v1
kind: Pod
mrtadata:
  name: app-secret
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readonly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecrret1