apiVersion: v1
kind: Pod
metadata:
  name: app-secret-env
  spec:
    containers:
    - name: mycontauner
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret1
              key: SECRET_USERNAME
        - name: SECRED_PASSWORD
          valueFROM:
            secretKeyRef:
              name: mysecret1
              key: password
    restartPolicy: Never